/*
 * Fry & Fork — menu data (single source of truth for the whole site).
 *
 * Prices are the live WEBSITE prices in pounds. To change a price, edit it here.
 *   price: 9.00               -> one price
 *   price: [6.49, 8.30, 12.10] -> one price per size, matching the category's `sizes`
 *   opts:  [[label, price], …] -> named options (used by Meal Deal 2)
 * tags: v = vegetarian, hot = spicy, new = new dish, chef = chef's pick
 * pcs:  piece count shown next to the name
 */
window.FF_MENU = {
  batterAddOn: 0.50,
  categories: [
    {
      id: "deals", name: "Meal Deals", tab: "Deals", layout: "deals", note: "Feeding the whole house? Grab a box.",
      items: [
        { name: "Meal Deal 1", includes: ["16\" Margherita pizza", "Medium chips", "Garlic bread", "2 cans of juice"], price: 19.99 },
        { name: "Meal Deal 2", desc: "Pick your size:", opts: [["2× 10\" pizzas & 2 can drinks", 17.49], ["2× 12\" pizzas & 2 can drinks", 21.49], ["2× 16\" pizzas & a bottle drink", 29.49]] },
        { name: "Combo Box 1", includes: ["10\" Margherita pizza", "3× veg & 2× chicken pakora", "Doner", "Chips", "Salad & sauce", "Can of juice"], price: 17.49 },
        { name: "Combo Box 2", includes: ["Margherita pizza", "3× veg & 3× chicken pakora", "Doner", "Chips", "Salad & sauce", "2 cans of juice"], price: 20.49 },
        { name: "Chippy Box", includes: ["1× jumbo sausage", "1× hamburger", "Large fish", "1× mince pie or homemade steak pie", "Medium chips", "2 cans"], price: 21.49 },
        { name: "Crunchy Box", includes: ["Half pizza crunch", "Onion rings", "Battered mushrooms", "Potato fritters", "Chips", "Can of juice"], price: 15.49 },
        { name: "Chicken Box", includes: ["5× spicy wings", "1× chicken steak", "1× spicy chicken steak", "12× popcorn chicken", "10× chicken nuggets", "Medium chips", "2 cans of juice"], price: 22.49 },
        { name: "Family Box", includes: ["2× jumbo sausage", "2× hamburgers", "1× fried pizza", "Large fish", "Homemade steak pie or mince pie", "Large chips", "Big bottle of juice"], price: 25.49 },
      ],
    },
    {
      id: "fish", name: "Fish Bar", tab: "Fish Bar", sizes: ["Single", "Supper"], note: "Single on its own, or make it a supper with chips.",
      items: [
        { name: "Large Fish", price: [9.49, 11.50] },
        { name: "Fish Cake", price: [4.49, 6.80] },
        { name: "Scampi", price: [5.70, 7.70], pcs: 10 },
        { name: "Jumbo Smoked Sausage (Battered)", price: [5.50, 8.20] },
        { name: "Jumbo Smoked Sausage", price: [4.30, 7.40] },
        { name: "Jumbo Sausage", price: [4.30, 7.00], pcs: 2 },
        { name: "Hamburger", price: [4.30, 7.00] },
        { name: "White Pudding", price: [4.30, 7.00] },
        { name: "Black Pudding", price: [4.30, 7.00] },
        { name: "Haggis Pudding", price: [4.30, 7.20] },
        { name: "Jumbo Haggis", price: [4.30, 7.30] },
        { name: "King Rib", price: [4.30, 7.30] },
        { name: "Rump Steak", price: [4.30, 7.20] },
        { name: "Cheese N Burger", desc: "Homemade", price: [4.80, 8.20] },
        { name: "Mince Pie", price: [4.30, 7.40] },
        { name: "Homemade Steak Pie", price: [4.30, 7.40] },
        { name: "Fried Pizza", price: [4.60, 7.30] },
        { name: "Half Fried Pizza", price: [3.49, 6.30] },
        { name: "Fried Pizza Crunch", price: [5.49, 8.20] },
        { name: "Half Fried Pizza Crunch", price: [3.90, 7.10] },
      ],
    },
    {
      id: "chips", name: "Chips", tab: "Chips",
      items: [
        { name: "Medium Chips", price: 3.20 },
        { name: "Large Chips", price: 5.49 },
        { name: "Chips & Curry Sauce", price: 5.00 },
        { name: "Chip Roll", price: 3.10 },
        { name: "Medium Chips & Cheese", price: 5.20 },
        { name: "Large Chips & Cheese", price: 7.00 },
        { name: "Chips & Doner", price: 7.20 },
        { name: "Chips & Pesto", price: 5.50 },
        { name: "Chips & Bolognese", price: 6.80 },
        { name: "Chips, Cheese & Doner Meat", price: 7.70 },
        { name: "Chips, Cheese, Doner & Curry Sauce", price: 9.20 },
        { name: "Chips, Cheese & Gravy", price: 6.70 },
        { name: "Chips, Cheese & Curry Sauce", price: 6.50 },
      ],
    },
    {
      id: "pizza", name: "Pizzas", tab: "Pizza", sizes: ["10\"", "12\"", "16\""], note: "Made on fresh, homemade dough.",
      items: [
        { name: "Margherita", desc: "Homemade tomato sauce & mozzarella cheese", price: [6.49, 8.30, 11.60] },
        { name: "Create Your Own Pizza", price: [6.49, 8.30, 11.60] },
        { name: "Tre Formaggi", desc: "Homemade tomato sauce, mozzarella, parmesan & gorgonzola", price: [7.49, 8.00, 12.99] },
        { name: "Hawaiian", desc: "Homemade tomato sauce, mozzarella cheese, ham & pineapple", price: [8.49, 10.99, 15.99] },
        { name: "Funghi", desc: "Homemade tomato sauce, mozzarella cheese & mushrooms", price: [8.49, 9.99, 14.50] },
        { name: "Stagoni", desc: "Homemade tomato sauce, mozzarella cheese, ham, mushrooms, artichokes & spicy sausage", price: [9.49, 11.60, 16.99] },
        { name: "Campagnola", desc: "Homemade tomato sauce, mozzarella cheese, anchovies & black olives", price: [8.49, 10.50, 16.50] },
        { name: "Pacanti (Pepperoni)", desc: "Homemade tomato sauce, mozzarella cheese & spicy sausage", price: [8.49, 10.50, 16.50], tags: ["hot"] },
        { name: "Napolitana", desc: "Homemade tomato sauce, mozzarella cheese, anchovies & black olives", price: [8.49, 10.50, 15.50] },
        { name: "Favorita", desc: "Homemade tomato sauce, mozzarella cheese, chicken, olives & peppers", price: [8.49, 10.20, 14.80] },
        { name: "Salami", desc: "Homemade tomato sauce, mozzarella cheese & Italian salami", price: [8.49, 10.99, 14.99] },
        { name: "Valentino", desc: "Homemade tomato sauce, mozzarella cheese, peppers, spicy sausage, Italian sausage & Italian salami", price: [8.49, 10.20, 15.50] },
        { name: "Grantourco", desc: "Homemade tomato sauce, mozzarella cheese, chicken & sweetcorn", price: [8.49, 10.20, 16.50] },
        { name: "Pollo Alla Pesto", desc: "Homemade tomato sauce, pesto, mozzarella cheese & chicken", price: [8.49, 9.70, 14.50] },
        { name: "Mexicana", desc: "Homemade tomato sauce, mozzarella cheese, chicken, peppers, onions & chilli", price: [8.70, 10.60, 16.50], tags: ["hot"] },
        { name: "Sicili", desc: "Homemade tomato sauce, mozzarella cheese, mushrooms, pepperoni & onion", price: [9.00, 10.99, 15.50] },
        { name: "Diavola", desc: "Homemade tomato sauce, mozzarella cheese, peppers, chilli & spicy sausage", price: [9.00, 10.99, 15.50], tags: ["hot"] },
        { name: "Mantarana", desc: "Homemade tomato sauce, mozzarella cheese, spicy sausage, onions & peppers", price: [9.00, 10.99, 15.50] },
        { name: "Cardinal", desc: "Homemade tomato sauce, mozzarella cheese, ham & mushrooms", price: [9.00, 10.99, 15.50] },
        { name: "Vegetarian", desc: "Homemade tomato sauce, mozzarella cheese, artichokes, peppers, onions, mushrooms & jalapeños", price: [9.00, 11.50, 16.50], tags: ["v"] },
        { name: "Bianca", desc: "Homemade tomato sauce, mozzarella cheese, ham, spicy sausage & jalapeños", price: [9.00, 10.50, 16.00] },
        { name: "Norcia", desc: "Homemade tomato sauce, mozzarella cheese, mushrooms, pepperoni & peppers", price: [9.00, 11.20, 15.70] },
        { name: "Veronese", desc: "Homemade tomato sauce, mozzarella cheese, mushrooms & Parma ham", price: [9.00, 10.99, 14.99] },
        { name: "Volcano", desc: "Homemade tomato sauce, mozzarella cheese, spicy sausage, chicken, olives & jalapeños", price: [9.00, 10.99, 14.99], tags: ["hot"] },
        { name: "Sorrento", desc: "Homemade tomato sauce, mozzarella cheese, spicy sausage, chicken & red onion", price: [9.00, 9.80, 15.50] },
        { name: "Caprina", desc: "Homemade tomato sauce, mozzarella cheese, bacon, Italian spicy sausage & mixed peppers", price: [9.30, 10.99, 15.50], tags: ["new"] },
        { name: "Barbecue Chicken", desc: "Homemade tomato sauce, mozzarella cheese with barbecued chicken", price: [9.30, 10.99, 15.50], tags: ["new"] },
        { name: "Marinara", desc: "Homemade tomato sauce, mozzarella cheese with mixed seafood", price: [9.30, 10.99, 15.50] },
        { name: "Capricosa", desc: "Homemade tomato sauce, mozzarella cheese, mushrooms, peppers, black olives & pepperoni", price: [9.49, 11.60, 16.50] },
        { name: "Prosciutto", desc: "Homemade tomato sauce, mozzarella cheese & Italian Parma ham", price: [9.49, 11.60, 17.50] },
        { name: "Doner", desc: "Homemade tomato sauce, mozzarella cheese & doner meat", price: [9.49, 11.60, 18.99] },
        { name: "Chef Special", desc: "Homemade tomato sauce, mozzarella, smoked sausage, onion & pineapple", price: [9.49, 10.80, 15.50] },
        { name: "Meat Feast", desc: "Chicken, spicy mince, ham & spicy sauce", price: [9.50, 12.00, 17.50] },
        { name: "Nostara", desc: "Tomato, mozzarella, spicy chicken, spicy sausage & mushrooms", price: [9.30, 11.50, 16.99] },
      ],
    },
    {
      id: "calzones", name: "Calzones", tab: "Calzones",
      items: [
        { name: "Calzone", desc: "Homemade tomato sauce, mozzarella cheese, mushrooms, ham & spicy sausage", price: 10.49 },
        { name: "Calzone Doner", desc: "Homemade tomato sauce, mozzarella cheese & doner meat", price: 11.99 },
        { name: "Calzone Vegetable", desc: "Homemade tomato sauce, mozzarella cheese, mushrooms, artichokes, peppers, onions & olives", price: 9.99, tags: ["v"] },
        { name: "Chicken Hoagie Calzone", desc: "Homemade tomato sauce, peppers, onions, chicken, chips, cheese & mozzarella cheese", price: 14.49 },
        { name: "Doner Hoagie Calzone", desc: "Homemade tomato sauce, chips, cheese & doner meat", price: 13.99 },
        { name: "Mixed Hoagie Calzone", desc: "Homemade tomato sauce, chips & cheese, doner, chicken, green peppers & onions", price: 15.99 },
      ],
    },
    {
      id: "pasta", name: "Pasta", tab: "Pasta", note: "All cooked by our professional chef, and every pasta comes with parmesan.",
      items: [
        { name: "Penne Vegetarian", desc: "Homemade tomato sauce, broccoli, mushrooms, artichokes, garlic & olives", price: 9.50, tags: ["v"] },
        { name: "Penne Napoli", desc: "Homemade tomato sauce, garlic & basil", price: 8.49 },
        { name: "Penne Funghi Crema", desc: "Mushrooms, garlic & cream sauce", price: 9.50 },
        { name: "Penne Della Casa", desc: "Homemade tomato sauce, peppers, onions & spicy sausage", price: 9.50 },
        { name: "Penne Alla Pesto", desc: "Homemade pesto, homemade tomato sauce & cream", price: 9.00 },
        { name: "Penne Ducale", desc: "Homemade tomato sauce, mushrooms, chicken, garlic & a kiss of pesto & cream", price: 10.99 },
        { name: "Penne Sicilliana", desc: "Homemade tomato sauce, cream, chicken, onion, blue cheese & broccoli", price: 11.50 },
        { name: "Penne Alla Formage", desc: "Gorgonzola, parmesan & mozzarella cooked in a garlic cream sauce", price: 9.49 },
        { name: "Penne Alfredo", desc: "Chicken & broccoli cooked in a rich gorgonzola cream sauce", price: 11.50 },
        { name: "Penne Alla Carbozola", desc: "Smoky sausage & mushroom in a garlic & creamy blue cheese sauce", price: 11.80 },
        { name: "Penne Alla Barese", desc: "Smoky sausage & broccoli in a cream & homemade tomato sauce", price: 11.80 },
        { name: "Penne Alla Genovese", desc: "Pesto, chicken & mushroom in a garlic & creamy sauce", price: 11.50, tags: ["chef"], flag: "Please try, chef's favourite!" },
        { name: "Spaghetti Carbonara", desc: "Bacon, garlic & cream", price: 9.49 },
        { name: "Spaghetti Arrablata", desc: "Homemade tomato sauce, garlic & chilli", price: 8.49, tags: ["hot"] },
        { name: "Spaghetti Amatriciana", desc: "Homemade tomato sauce, bacon, garlic & onions", price: 9.49 },
        { name: "Spaghetti Bolognese", desc: "Homemade tomato sauce, minced beef & garlic", price: 10.99 },
        { name: "Spaghetti Marinara", desc: "Mixed seafood, homemade tomato sauce, onions, garlic & a kiss of chilli", price: 12.50 },
        { name: "Tagliatelle Papalina", desc: "Onions, mushrooms, bacon, peas, blue cheese & cream sauce", price: 12.50 },
        { name: "Tagliatelle Chef Special", desc: "Homemade tomato sauce, cream, mushroom, bolognese & spicy sausage", price: 11.80, tags: ["chef"], flag: "Please try!" },
        { name: "Tagliatelle Ciociara", desc: "Homemade tomato sauce, mushrooms, ham, peas, garlic & a touch of cream", price: 9.99 },
        { name: "Gnocchi Alforno", desc: "Homemade potato dumplings in tomato & cream sauce, topped with mozzarella", price: 10.99 },
        { name: "Gnocchi Alla Romana", desc: "Homemade potato dumplings cooked with spinach, gorgonzola cheese & cream", price: 11.50 },
        { name: "Tortellini Della Casa", desc: "Spinach & chicken cooked in a lovely cream & homemade tomato sauce", price: 11.50 },
        { name: "Tortellini Alferno", desc: "Cooked in tomato & cream sauce with a kiss of pesto, topped with mozzarella cheese", price: 11.50 },
        { name: "Tortellini Funghi Alla Crema", desc: "Mushrooms cooked in a cream cheese sauce, topped with mozzarella cheese", price: 11.50 },
      ],
    },
    {
      id: "risotto", name: "Risotto", tab: "Risotto", note: "All cooked by our professional chef.",
      items: [
        { name: "Risotto Funghi E Crema", desc: "Rice cooked with mushrooms, onions, garlic & cream", price: 9.00 },
        { name: "Risotto Fattore", desc: "Rice cooked with chicken & spinach in a tomato & cream sauce", price: 10.50 },
        { name: "Risotto Mariyanara", desc: "Rice cooked with mixed seafood, onions, garlic & a kiss of chilli in homemade tomato sauce", price: 11.20 },
        { name: "Risotto Della Casa", desc: "Rice cooked with mushrooms, ham, peas & onions in a tomato & cream sauce", price: 10.50 },
        { name: "Risotto Pollo Funghi Crema", desc: "Rice cooked with chicken & mushrooms in a creamy garlic sauce", price: 9.99 },
        { name: "Risotto Sorrentina", desc: "Rice cooked with onion, smoked sausage & ham in a creamy homemade tomato sauce", price: 11.50 },
      ],
    },
    {
      id: "italian-sides", name: "Italian Sides", tab: "Italian Sides",
      items: [
        { name: "Focaccia", desc: "Pizza bread topped with rosemary", price: 4.00 },
        { name: "Focaccia Con Mozzarella", desc: "Pizza bread with cheese", price: 6.10 },
        { name: "Focaccia Piccante", desc: "Pizza bread with spicy homemade tomato sauce", price: 4.80, tags: ["hot"] },
        { name: "Focaccia Alla Parma", desc: "Pizza bread with cheese, topped with Italian Parma ham", price: 6.70 },
        { name: "Focaccia Bruschetta", desc: "Pizza bread topped with fresh tomato", price: 6.10 },
        { name: "Funghi Aglio", desc: "Fried garlic mushrooms", price: 4.20 },
        { name: "Funghi Alla Crema", desc: "Mushrooms cooked in a cream cheese sauce, topped with mozzarella cheese & oven baked", price: 4.80 },
      ],
    },
    {
      id: "burgers", name: "Burgers", tab: "Burgers", sizes: ["¼lb", "½lb"], note: "All served with salad, chips & sauce.",
      items: [
        { name: "Pounder Burger", price: [6.30, 8.00] },
        { name: "Pounder Cheese Burger", price: [7.45, 9.00] },
        { name: "Pounder Cheese & Bacon Burger", price: [8.40, 9.45] },
        { name: "Pounder with Doner Meat Burger", price: [8.45, 9.20] },
        { name: "Chicken Burger", price: 7.00 },
        { name: "Zinger Burger", price: 7.00 },
      ],
    },
    {
      id: "kebabs", name: "Kebabs & Wraps", tab: "Kebabs", note: "Kebabs are served with separate salad & sauces.",
      items: [
        { name: "Doner Kebab", price: 9.00 },
        { name: "Chicken Kebab", price: 9.99 },
        { name: "Mixed Kebab", price: 11.50 },
        { name: "Doner Meat", price: 6.70 },
        { name: "Doner Wrap", price: 9.50 },
        { name: "Chicken Wrap", price: 10.99 },
        { name: "Mixed Wrap", desc: "Doner & chicken kebab", price: 12.20 },
        { name: "Hoagie Wrap", desc: "Chips, cheese, salad & doner", price: 11.50 },
        { name: "Chips & Cheese Wrap", price: 4.70 },
        { name: "Chicken Royal Wrap", price: 6.30 },
        { name: "Spicy Chicken Royal Wrap", price: 6.50, tags: ["hot"] },
        { name: "Mixed Hoagie Wrap", desc: "Serves 2. Salad, chicken, doner, chips, cheese & your choice of sauce", price: 13.80 },
      ],
    },
    {
      id: "chicken", name: "Chicken", tab: "Chicken", sizes: ["Single", "Supper"], note: "Add batter to a ¼ or ½ chicken for £0.50.",
      items: [
        { name: "¼ Chicken", price: [6.00, 8.49] },
        { name: "Half Chicken", price: [8.49, 10.99] },
        { name: "Chicken Nuggets", price: [4.70, 6.50], pcs: 8 },
        { name: "Chicken Steak", price: [4.60, 8.20], pcs: 2 },
        { name: "Spicy Chicken Wings", price: [5.00, 7.00], pcs: 5, tags: ["hot"] },
        { name: "Chicken Popcorn", price: [4.09, 5.60], pcs: 12 },
      ],
    },
    {
      id: "pakora", name: "Pakora", tab: "Pakora", note: "Homemade pakora, served with salad & sauce.",
      items: [
        { name: "Mixed Pakora", desc: "4 chicken & 5 veg pieces", price: 7.30 },
        { name: "Vegetable Pakora", price: 6.00, pcs: 8, tags: ["v"] },
        { name: "Chicken Pakora", price: 7.00, pcs: 6 },
      ],
    },
    {
      id: "rolls", name: "Hot Filled Rolls", tab: "Rolls",
      items: [
        { name: "Hamburger Roll", price: 2.70 },
        { name: "Hamburger Chip Roll", price: 5.00 },
        { name: "Sausage Roll", price: 2.70 },
        { name: "Sausage Chip Roll", price: 5.00 },
        { name: "Cheese N Burger Roll", price: 5.40 },
        { name: "Veggie Burger Roll", price: 3.49, tags: ["v"] },
        { name: "Fritter Roll", price: 3.49, pcs: 4 },
        { name: "Doner Roll", price: 4.70 },
      ],
    },
    {
      id: "vegetarian", name: "Vegetarian", tab: "Vegetarian", sizes: ["Single", "Supper"], note: "Single on its own, or make it a supper with chips.",
      items: [
        { name: "Veggie Burger", desc: "Comes in a bun with salad", price: [4.00, 6.00], tags: ["v"] },
        { name: "Veggie Spring Roll", price: [3.49, 5.49], pcs: 2, tags: ["v"] },
        { name: "Vegetable Pakora", price: [6.00, 8.20], pcs: 7, tags: ["v"] },
        { name: "Pitta Salad", price: [3.00, 5.00], tags: ["v"] },
      ],
    },
    {
      id: "sides", name: "Side Orders", tab: "Sides",
      items: [
        { name: "Mozzarella Sticks", price: 4.00 },
        { name: "Onion Rings", price: 4.49 },
        { name: "Battered Mushrooms", price: 4.49 },
        { name: "Mixed Salad", price: 3.49 },
        { name: "Fritters", price: 4.90, pcs: 10 },
        { name: "Mushy Peas", price: 1.10 },
        { name: "Gravy Sauce", price: 1.10 },
        { name: "Curry Sauce", price: 1.10 },
        { name: "Battered Mars Bar", price: 2.90 },
        { name: "Battered Snickers Bar", price: 3.45 },
        { name: "Rolls", price: 0.70 },
        { name: "Dips", price: 0.35 },
        { name: "Jar of Mussels", price: 3.70 },
        { name: "Chippy Sauce", price: 3.70 },
      ],
    },
    {
      id: "kids", name: "Kids Meals", tab: "Kids", layout: "kids", note: "Every kids meal comes with chips, a bottle of Fruit Shoot & a lollipop.",
      items: [
        { name: "Jumbo Sausage", price: 5.00, pcs: 1 },
        { name: "Hamburger", price: 5.00, pcs: 1 },
        { name: "Fishcake", price: 5.00, pcs: 1 },
        { name: "Chicken Steak", price: 5.00, pcs: 1 },
        { name: "Chicken Nuggets", price: 5.00, pcs: 4 },
        { name: "Scampi", price: 5.00, pcs: 5 },
        { name: "Chicken Popcorn", price: 5.00, pcs: 10 },
      ],
    },
    {
      id: "desserts", name: "Desserts", tab: "Desserts",
      items: [
        { name: "Strawberry Cheesecake", price: 5.10 },
        { name: "Tiramisu", price: 5.10 },
        { name: "Chocolate Gateau", price: 4.80 },
        { name: "Mars Bar", price: 1.70 },
        { name: "Snickers", price: 1.70 },
        { name: "Ben & Jerry's Ice Cream", desc: "Chocolate Fudge Brownie, Cookie Dough, Caramel Chew Chew, Half Baked, Peanut Buttercup or Phish Food", price: 6.90 },
      ],
    },
    {
      id: "drinks", name: "Soft Drinks", tab: "Drinks",
      items: [
        { name: "Can", desc: "330ml", price: 1.20 },
        { name: "Bottle", desc: "500ml", price: 2.10 },
        { name: "Big Bottle", price: 3.49 },
        { name: "Water", desc: "750ml", price: 1.20 },
      ],
    },
  ],
};
